### ISSUE TITLE
It will be great if we can create sidebar link

### ISSUE THREAD

**Issue by pluveto** [FriendsOfFlarum/links#17]
Like this
![image](https://user-images.githubusercontent.com/50045289/79064546-517cbc80-7cdc-11ea-84f6-6a26ba818d99.png)

**Comment by clarkwinkelmann** [comment]
From a technical standpoint, it wouldn't be much different from what we have for main menu links.

The question however would be, should it be made into its own separate extension or added into this one.

If we do that inside the existing extension, we'll need a whole additional tab with the list of links for that other menu. And we will need some way to store which links belong to which menu.

Nothing too challenging, but it will require a bit of work.

I think those are the kind of features that would likely be developed as commissioned work and added to the FoF extension.

**Comment by DavideIadeluca** [comment]
@pluveto https://github.com/davwheat/flarum-ext-custom-sidenav-links should resolve your feature request
