### ISSUE TITLE
Make links visible to logged in users only

### ISSUE THREAD

**Issue by lbausch** [FriendsOfFlarum/links#23]
Is it possible to make links visible to logged in users only?
I would also appreciate hints for a possible implementation, so maybe I can submit a pull request.

**Comment by luceos** [comment]
The back end has to reduce the given links dataset. The hardship is allowing configuration of what permission groups have access to which links in the admin area. I've seen such an implementation by @clarkwinkelmann somewhere, not sure where though..

**Comment by clarkwinkelmann** [comment]
I have implemented something like this in the premium extension Formulaire, where you can choose permissions for each individual field in a form.

It's not extremely complex, but I think it's too complex for this extension if we want to keep is as easy as possible to maintain.

However we could have a permission to see the whole menu, and not for individual links.

**Comment by sburkett** [comment]
> The back end has to reduce the given links dataset.

I have to believe that we are likely only talking about just a few pages on a typical Flarum site.

> The hardship is allowing configuration of what permission groups have access to which links in the admin area

I'm not sure I would call it "hardship". A feature such as making certain things visible only to members, groups, etc. is pretty standard fare, tbh. You have permission groups that can theoretically be assigned to anything, be them pages, tags, etc. Makes no sense that links can't be restricted in this way.

The current behavior of clicking a link that you can't view simply results in a "page not found" error. Not the experience a site admin is likely going for :).

Just my 2cp :)

**Comment by imorland** [comment]
Available in version `0.5.1`
