### ISSUE TITLE
Beta 14 support?

### ISSUE THREAD

**Issue by AlexanderOMara** [FriendsOfFlarum/links#27]
Flarum beta 14 has been out for about a week, any hope for an update to support this version?

Is this pull request all that's needed? https://github.com/FriendsOfFlarum/links/pull/24

**Comment by clarkwinkelmann** [comment]
As announced, the Friends Of Flarum group is working hard to get the extensions updated in the shortest amount of time possible https://discuss.flarum.org/d/16242-friends-of-flarum-the-collaboration-for-maintained-extensions/33

We will use the extension discussion on Flarum Discuss to announce updates. Until that happens, extensions should be considered not compatible. To keep our workload to a minimum, I'm closing this issue and we'll post updates on the forum.

If you would like to help us, see the link above for some suggestions. Thanks!
