### ISSUE TITLE
links are positioning over logo

### ISSUE THREAD

**Issue by murdocklawless** [FriendsOfFlarum/links#47]
how can I slide links to the right?

**Comment by datitisev** [comment]
You can probably add some margin with CSS - would need to make sure it looks fine on mobile though.

Preferably we'd find the cause for the links appearing over the logo. How is your logo added? Does it do anything custom?
The links work just fine on the [Flarum Community](https://discuss.flarum.org/).

**Comment by murdocklawless** [comment]
I searched in css file but I couldn't found where to add margin?

**Comment by dsevillamartin** [comment]
Closing due to stale - hope you managed to find an answer, apologies for not following up.
