### ISSUE TITLE
Specify how to use translations in Title

### ISSUE THREAD

**Issue by Borderliner** [FriendsOfFlarum/links#64]
Please specify in docs or somewhere how we can use translation strings instead of hardcoding the link title, thank you.

**Comment by clarkwinkelmann** [comment]
This is not a feature of this extension. Links are not translatable.

It seems like this paid extension implements the feature you describe. It's not offered/maintained by FriendsOfFlarum though https://discuss.flarum.org/d/30487-localizd-truly-multi-lingual

If you have some programming knowledge, it wouldn't be very difficult to skip extensions and directly inject links in the desired language using Flarum's javascript API, maybe taking inspiration and CCS style from FoF Links.
