### ISSUE TITLE
Unable to update to version 0.2.0

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/links#7]
Hi, when i run `composer update fof/links` for update the plugin I see system stay frozen on:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

the cursor continue to intermitting without complete the update.

**Comment by PeopleInside** [comment]
Resolved... after many try.

**Comment by luceos** [comment]
Use composer require fof/links when your previous constraint is lower than the newly released version. Composer will block these updates in case this might impact your stability constraint.

Eg configured is `0.1` and new version is `0.2`, composer will block when using `update`, so use `require`.

**Comment by PeopleInside** [comment]
Ok maybe this was resolving my issue i tried that, Take some time but was able to update. Thanks @luceos  :) hope you are well.
